config/routes.rb
Rails.application.routes.draw do


  devise_for :users
resources :activities
resources :items
resources :devise
root to: 'activities#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :items


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
has_many :activities

  def to_s
    "#{things}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = current_user.activities if current_user
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user_id = current_user.id
    @activity.save

    redirect_to activities_path
  end

  def edit
    @activity = Activity.find(params[:id])

  end

  def update
    @activity = Activity.find(params[:id])
    @activity.update(activity_params)
    redirect_to activities_path
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to activities_path
  end

  private
  def activity_params
  params.require(:activity).permit(:name, :items_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
     @items = Item.all
  end

  def show
    @item= Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item= Item.find(params[:id])
    @item.update(item_params)
    redirect_to items_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to items_path
  end

  private
  def item_params
  params.require(:item).permit(:thing)
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/creat.html.erb
<h1>Activities#creat</h1>
<p>Find me in app/views/activities/creat.html.erb</p>

app/views/activities/destroy.html.erb
<h1>Activities#destroy</h1>
<p>Find me in app/views/activities/destroy.html.erb</p>

app/views/activities/edit.html.erb
<div class="text-center">
<h1>Edit activities <%= @activity.name %></h1>
</div>
<%= simple_form_for @activity do |f| %>
<div class="container shadow bg-white rounded my-5 p-4">
<div class="row">
<div class="col-8">
<%= f.input :name %>
</div>

    <div class="col-8">
     <%= f.collection_check_boxes :items_id, Item.all, :id, :thing %>
    </div>


</div>

<div class="text-right">
<%= f.button :submit, class: "btn btn-primary" %>
</div>
</div>
<% end %>

app/views/activities/index.html.erb
<div class="text-center">
<h1>Mes activités</h1>
</div>
<div class="container">
<div class="row">



<% @activities.each do |activity| %>
<div class="col-12">
<div class="shadow bg-white rounded p-4 d-flex justify-content-between">
<h2><%= activity.name %></h2>
<%= activity.items_id %>
<p><b><%= activity.created_at.strftime("%D") %></b></p>
</div>
</div>
<%= link_to "voir activité", activity_path(activity.id) %>
<% end %>
<%= link_to "Ajouter activité", new_activity_path %>


<%= link_to "Ajouter item", new_item_path %>
  <p>Pour faire du txt</p>
<%= link_to "sortir", destroy_user_session_path, method: :delete %>
</div>
</div>

app/views/activities/new.html.erb
<div class="text-center">
<h1>Create a New activity</h1>
</div>
<%= simple_form_for @activity do |f| %>
<div class="container shadow bg-white rounded my-5 p-4">
  <div class="row">
    <div class="col-8">
      <%= f.input :name %>
    </div>
  </div>

   <div class="row">
    <div class="col-8">
     <%= f.collection_check_boxes :items_id, Item.all, :id, :thing %>
    </div>
  </div>

  <div class="text-right">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/activities/show.html.erb
<div class="container shadow bg-white rounded p-4 text-center my-5 mb-4">
<h1><%= @activity.name %></h1>
<p>ça m'énerve</p>
<h2><%= @activity.items_id %></h2>

<h2><%= @activity.created_at.strftime("%d %b %Y") %></h2>

<%= link_to "Destroy", activity_path(@activity.id), method: :delete, class: "btn
btn-danger" %>
<%= link_to "Edit", edit_activity_path(@activity.id), class: "btn
btn-danger" %>
</div>

app/views/activities/update.html.erb
<h1>Activities#update</h1>
<p>Find me in app/views/activities/update.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<div class="text-center">
<h1>Liste des Items</h1>
</div>
<div class="container">
<div class="row">
<% @items.each do |item| %>
<div class="col-12">
<div class="shadow bg-white rounded p-4 d-flex justify-content-between">
<h2><%= item.thing %></h2>
<p><b><%= item.created_at.strftime("%D") %></b></p>
</div>
</div>
<% end %>
<%= link_to "Ajouter item", new_item_path %>
<%= link_to "Retour à la liste des activités", activities_path, method: :get %>


</div>
</div>

app/views/items/new.html.erb
<div class="text-center">
<h1>Create a New Item</h1>
</div>
<%= simple_form_for @item do |f| %>
<div class="container shadow bg-white rounded my-5 p-4">
  <div class="row">
    <div class="col-8">
      <%= f.input :thing %>
    </div>
  </div>

  <div class="text-right">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pensebete</title>
    <%= csrf_meta_tags %>

    <!--boostrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <!-- fin boostrap -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>